services:
  minio:
    image: minio/minio:latest
    command: server /data --address ":${MINIO_HTTPPORT}" --console-address ":${MINIO_CONSOLEPORT}"
    ports:
      - "${MINIO_HTTPPORT}:9000"
      - "${MINIO_CONSOLEPORT}:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 1s
    restart: always
    depends_on:
      vault:    
  mc:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    network_mode: service:minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://localhost:${MINIO_HTTPPORT} ${MINIO_USER} ${MINIO_PASSWORD};
      mc mb --ignore-existing myminio/${MINIO_BUCKET};
      mc anonymous set public myminio/${MINIO_BUCKET};
      "
volumes:
  minio-data:  