services:
  api_db:
    container_name: api-db
    build: ./postgres-with-curl
    restart: always  # Always restart the container if it stops
    environment:
      POSTGRES_USER: ${APIPOSTGRES_USER}                   # Set the PostgreSQL username
      POSTGRES_PASSWORD: ${APIPOSTGRES_PASSWORD}           # Set the PostgreSQL password
      POSTGRES_DB:  ${APIPOSTGRES_DB}                      # Set the default database name
    ports:
      - "${APIPOSTGRES_PORT}:5432"  # Map port 5432 on the host to port 5432 in the container
    volumes:
      - api-postgres:/var/lib/postgresql/data  # Persist data even if the container is removed
    depends_on:
      - minio
      - vault
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULTEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULTPASSWORD}
    depends_on:
      - api_db      
volumes:
  api-postgres:
  pgadmin-data: