services:
  vault:
    container_name: vault-docker
  vault_seed:
    container_name: vault-seed-docker
  minio:
    container_name: minio-docker
    depends_on:
      - vault
  minio_mc:
    container_name: minio-mc-docker
  api_db:
    container_name: api-db-docker
    depends_on:
      - minio
      - vault    
  pgadmin:
    container_name: pgadmin-db-docker
  temporal_db:
    container_name: temporalpostgresql-docker
    depends_on:
      - vault    
  temporal:
    container_name: temporal-docker
  temporal_admin_tools:
    container_name: temporal-admin-tools-docker
  temporal_ui:
    container_name: temporal-ui-docker
  service_api:
    container_name: service-api-docker
    depends_on:
      - vault
      - minio
      - minio_mc
      - api_db
      - temporal    