services:
  vault:
    container_name: vault-local
  vault_seed:
    container_name: vault-seed-local
  minio:
    container_name: minio-local
    depends_on:
      vault:
        condition: service_started
      vault_seed:
        condition: service_healthy
  minio_mc:
    container_name: minio-mc-local
  api_db:
    container_name: api-db-local
    depends_on:
      minio:
        condition: service_healthy
      vault:
        condition: service_started
      vault_seed:
        condition: service_healthy
  pgadmin:
    container_name: pgadmin-db-local
  temporal_db:
    container_name: temporalpostgresql-local
    depends_on:
      vault:
        condition: service_started
      vault_seed:
          condition: service_healthy
  temporal:
    container_name: temporal-local
  temporal_admin_tools:
    container_name: temporal-admin-tools-local
  temporal_ui:
    container_name: temporal-ui-local