services:
  vault:
    container_name: vault-docker
  vault_seed:
    container_name: vault-seed-docker
  minio:
    container_name: minio-docker
    depends_on:
      vault:
        condition: service_started
      vault_seed:
        condition: service_healthy
  minio_mc:
    container_name: minio-mc-docker
  api_db:
    container_name: api-db-docker
    depends_on:
      minio:
        condition: service_healthy
      vault:
        condition: service_started
      vault_seed:
        condition: service_healthy
  pgadmin:
    container_name: pgadmin-db-docker
  temporal_db:
    container_name: temporalpostgresql-docker
    depends_on:
      vault:
        condition: service_started
      vault_seed:
          condition: service_healthy
  temporal:
    container_name: temporal-docker
  temporal_admin_tools:
    container_name: temporal-admin-tools-docker
  temporal_ui:
    container_name: temporal-ui-docker
  service_api:
    container_name: service-api-docker
    depends_on:
      vault:
        condition: service_started
      vault_seed:
        condition: service_healthy
      minio:
        condition: service_started      
      api_db:
        condition: service_started      
      temporal:
        condition: service_started      
  service_zipcode_worker:
    deploy:
      replicas: 3    
    depends_on:
      vault:
        condition: service_started
      vault_seed:
          condition: service_healthy
      minio:
        condition: service_started
      temporal:
        condition: service_started