services:
  service_api:
    image: ghcr.io/bochap-learning/bazel-temporal-fastapi/service_api:latest
    environment:
      VAULT_HOST: ${VAULT_HOST}
      VAULT_PORT: ${VAULT_PORT}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_PATH: ${VAULT_PATH}
    ports:
      - "8000:8000"
  